### ISSUE TITLE
Implement player camera

### ISSUE THREAD

**Issue by afiuorio** [afiuorio/jurassic-mendel#12]
Currently the map and the screen have the same dimensions. This will be hardly the case in our complete game. We need to implement a player camera.

**Comment by microfolk** [comment]
We could consider having maps be contained in a single screen! Some of the most famous games in the genre do this and some like Brogue still manage to offer beautiful and fun dungeons layout. We should think how we want our dungeons to be and then decide what do do with the camera.

**Comment by afiuorio** [comment]
For the moment I'll close this issue, if in the future we want bigger map we'll reopen it.
