### ISSUE TITLE
[LOW PRIORITY] Make border to map

### ISSUE THREAD

**Issue by afiuorio** [afiuorio/jurassic-mendel#7]
Currently the map doesn't have a border check, so the user can go outside of it and disappear. We need to either force a check or modify Map so that there is always a border wall.

**Comment by afiuorio** [comment]
This isn't necessary anymore since we have a room system.

**Comment by microfolk** [comment]
I'd actually posit that there is still a need for this check when we'll have the possibility to mine walls, but we'll think about it when it will be time
